openapi: 3.0.0
servers:
  - url: 'http://localhost:8080'
    description: ''
    variables: {}
info:
  version: a9daf1e5-c016-40e6-b9cb-a08166487905
  title: WIDGET
  description: ''
  termsOfService: ''
  contact: {}
  license:
    name: ''
paths:
  /api/widgets:
    post:
      summary: CREATE WIDGET
      operationId: CREATEWIDGET
      parameters:
        - $ref: '#/components/parameters/Content-Type'
      responses:
        '200':
          description: ''
          headers: {}
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: string
              example:
                xCoordinate: 1
                yCoordinate: 1
                zCoordinate: 4
                width: 205
                height: 100
            example: ' { "xCoordinate":1, "yCoordinate":1, "zCoordinate":4, "width":205, "height":100 }'
      tags:
        - WIDGETS API

    get:
      summary: GET ALL WIDGETS
      operationId: GETALLWIDGETS
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      tags:
        - WIDGETS API
    put:
      summary: UPDATE WIDGET
      operationId: UPDATEWIDGET
      parameters:
        - name: Content-Type
          in: header
          required: true
          style: simple
          schema:
            type: string
            example: application/json
      responses:
        '200':
          description: ''
          headers: {}
      tags:
        - WIDGETS API
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: string
              example:
                id: 2
                xCoordinate: 2
                yCoordinate: 1
                zCoordinate: 5
                width: 205
                height: 100
            example: '{ "id":2, "xCoordinate":2, "yCoordinate":1, "zCoordinate":5, "width":205, "height":100 }'
  /api/widgets/1:
    get:
      summary: GET WIDGET BY ID
      operationId: GETWIDGETBYID
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      tags:
        - WIDGETS API
    delete:
      summary: DELETE WIDGET
      operationId: DELETEWIDGET
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      tags:
        - WIDGETS API
components:
  parameters:
    Content-Type:
      name: Content-Type
      in: header
      required: true
      style: simple
      schema:
        type: string
        example: application/json
security: []
tags: []
externalDocs:
  url: ''
  description: ''
warnings: []
