openapi: 3.0.0
servers:
  - url: 'http://localhost:8080'
    description: ''
    variables: {}
info:
  version: a9daf1e5-c016-40e6-b9cb-a08166487905
  title: Widjet
  description: ''
  termsOfService: ''
  contact: {}
  license:
    name: ''
paths:
  /api/widgets:
    post:
      summary: CREATE WIDJET
      operationId: CREATEWIDJET
      parameters:
        - $ref: '#/components/parameters/Content-Type'
      responses:
        '200':
          description: ''
          headers: {}
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: string
              example:
                xCoordinate: 1
                yCoordinate: 1
                zCoordinate: 4
                width: 205
                height: 100
            example: ' { "xCoordinate":1, "yCoordinate":1, "zCoordinate":4, "width":205, "height":100 }'
      tags:
        - WIDJETS API

    get:
      summary: GET ALL WIDJETS
      operationId: GETALLWIDJETS
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      tags:
        - WIDJETS API
    put:
      summary: UPDATE WIDJET
      operationId: UPDATEWIDJET
      parameters:
        - name: Content-Type
          in: header
          required: true
          style: simple
          schema:
            type: string
            example: application/json
      responses:
        '200':
          description: ''
          headers: {}
      tags:
        - WIDJETS API
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: string
              example:
                id: 2
                xCoordinate: 2
                yCoordinate: 1
                zCoordinate: 5
                width: 205
                height: 100
            example: '{ "id":2, "xCoordinate":2, "yCoordinate":1, "zCoordinate":5, "width":205, "height":100 }'
  /api/widgets/1:
    get:
      summary: GET WIDJET BY ID
      operationId: GETWIDJETBYID
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      tags:
        - WIDJETS API
    delete:
      summary: DELETE WIDJET
      operationId: DELETEWIDJET
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      tags:
        - WIDJETS API
components:
  parameters:
    Content-Type:
      name: Content-Type
      in: header
      required: true
      style: simple
      schema:
        type: string
        example: application/json
security: []
tags: []
externalDocs:
  url: ''
  description: ''
warnings: []
