spring:
  profiles.active: development

---
spring:
  profiles: development
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: false
  h2: 
    console: 
      enabled: true

---

spring:
  profiles: production
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/db_example
    username: user
    password: pwd
    driver-class-name: com.mysql.cj.jdbc.Driver
---